### ISSUE TITLE
Erro apos a instalação

### ISSUE THREAD

**Issue by joaonivaldo** [rdehnhardt/skeleton#13]
Opa, acabei de instalar e seguir o passo a passo da instalação sem problemas. Mas quando rodei o npm run watch me deu o seguinte erro.
$ npm run watch

> @ watch D:\lixo\skeleton
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

D:\lixo\skeleton\node_modules\laravel-mix\setup\webpack.config.js:1
(function (exports, require, module, __filename, __dirname) { let path = require('path');
                                                              ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at requireConfig (D:\lixo\skeleton\node_modules\webpack\bin\convert-argv.js:96:18)
    at D:\lixo\skeleton\node_modules\webpack\bin\convert-argv.js:109:17
    at Array.forEach (native)

Como eu resolvo? 

Obrigado

**Comment by joaonivaldo** [comment]
era a minha versão do node que estava antiga.
